default:
  adapter: postgresql
  encoding: utf8
  host: localhost
  password: "<%= Figaro.env.POSTGRES_DB_PASSWORD %>"
  username: "<%= Figaro.env.POSTGRES_DB_USERNAME %>"
  pool: 5
development:
  adapter: postgresql
  database: kwangs_development
  encoding: utf8
  host: localhost
  password: "<%= Figaro.env.POSTGRES_DB_PASSWORD %>"
  username: "<%= Figaro.env.POSTGRES_DB_USERNAME %>"
  pool: 5
production:
  adapter: postgresql
  database: kwangs_production
  encoding: utf8
  password: "<%= ENV['POSTGRES_PR_PASSWORD'] %>"
  username: "<%= ENV['POSTGRES_PR_USERNAME'] %>"
  host: localhost
test:
  adapter: postgresql
  database: kwangs_test
  encoding: utf8
  host: localhost
  password: "<%= Figaro.env.POSTGRES_DB_PASSWORD %>"
  username: "<%= Figaro.env.POSTGRES_DB_USERNAME %>"
  pool: 5